// import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from './components/layout/Navbar'
import Footer from './components/layout/Footer'

// const inter = Inter({ subsets: ["latin"] });
// const openSans = Open_Sans({ subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
